version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "12:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    groups:
      dev-dependency:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "12:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    groups:
      dev-dependency:
        patterns:
          - "*"
